import 'dart:math';

/// 根据语言生成随机昵称（供首次展示/占位名替换使用）。
///
/// 设计目标：
/// - 中文可稍长、更有拟人感；
/// - 其他语言尽量短，避免 UI 侧栏/标题溢出；
/// - 仅用于“默认占位名”场景，不参与用户显式设置。
String generateRandomNicknameForLanguageCode(String languageCode) {
  final lang = languageCode.toLowerCase();
  final rand = Random();

  final options = switch (lang) {
    'zh' => const [
      '快乐的青蛙',
      '勇敢的猫咪',
      '温柔的熊猫',
      '闪亮的小星星',
      '悠闲的海獭',
      '勤劳的小蜜蜂',
      '会唱歌的海豚',
      '机灵的小狐狸',
      '小小的向日葵',
      '会飞的鱼',
      '会打鼓的小刺猬',
      '勤快的小仓鼠',
      '发光的萤火虫',
      '爱跳舞的企鹅',
      '聪明的小鼹鼠',
      '淘气的海马',
      '勇猛的小狮子',
      '爱读书的猫头鹰',
      '会冒泡的水獭',
      '软乎乎的小兔子',
      '会变魔术的猫',
      '微笑的松鼠',
      '慢吞吞的乌龟',
      '会冲浪的海豹',
      '会点灯的蚂蚁',
      '爱笑的小企鹅',
      '会滑翔的小鸟',
      '会滚圈的刺猬',
      '快乐的章鱼',
      '小小的星球旅人',
      '温暖的小暖炉',
      '会眨眼的向日葵',
      '爱飞的白鸽',
      '会追风的狐狸',
      '会抱抱的熊',
    ],
    'ja' => const [
      'ハッピーカエル',
      'ゆめねこ',
      'ほのぼのクマ',
      'きらきらウサギ',
      'スマイルコアラ',
      'まるマメ柴',
      'ひかるフクロウ',
      'のんびりタヌキ',
      'にこにこハムスター',
      'きもちいいシマリス',
      'あったかコーギー',
      'だいすきカメ',
      'てくてくペンギン',
      'ぴかぴかイルカ',
      'ふわふわ子ねこ',
      'ゆるゆるワニ',
      'きゅんきゅんネコ',
      'にこにこオウム',
      'まったりカピバラ',
      'のびのびパンダ',
      'つやつやキツネ',
      'ぽかぽかハリネズミ',
      'きらめくクラゲ',
      'のんびりカワウソ',
      'しあわせウサギ',
      'にこっとシカ',
      'ほしぞらフクロウ',
      'にゃんにゃんタヌキ',
      'すやすやコアラ',
      'スマイルミツバチ',
      'ぽよぽよリス',
      'ふわふわペンギン',
      'ハッピーカワウソ',
      'きらきらパンダ',
      'まるまるハム',
      'ぐるぐるタコ',
      'わくわくヒヨコ',
      'うきうきカメ',
    ],
    'ko' => const [
      '행복한 개구리',
      '해피 토끼',
      '미소 곰돌이',
      '반짝 고양이',
      '느긋한 수달',
      '용감한 여우',
      '귀여운 고래',
      '즐거운 벌',
      '포근한 토끼',
      '행복한 강아지',
      '달콤한 고양이',
      '웃는 팬더',
      '반짝이는 다람쥐',
      '신나는 펭귄',
      '용감한 개구리',
      '따뜻한 곰',
      '쾌활한 햄스터',
      '귀여운 고슴도치',
      '느긋한 거북이',
      '사랑스런 오리',
      '미소 짓는 너구리',
      '바람 부는 여우',
      '반짝이는 부엉이',
      '상큼한 돌고래',
      '유쾌한 바다사자',
      '달콤한 토끼',
      '포근한 판다',
      '즐거운 곰',
      '재미있는 문어',
      '웃음 많은 고래',
      '기분 좋은 고슴도치',
      '환한 비버',
      '따뜻한 카피바라',
      '반짝이는 오소리',
      '행복한 앵무새',
      '귀여운 새',
    ],
    'es' => const [
      'Sapo feliz',
      'Gato sonriente',
      'Oso amable',
      'Conejo brillante',
      'Delfín feliz',
      'Zorro valiente',
      'Cangrejo tranquilo',
      'Oveja curiosa',
      'Tortuga traviesa',
      'Koala cariñoso',
      'Perrito alegre',
      'Raton curioso',
      'Zorrito pícaro',
      'Oso tranquilo',
      'Conejo valiente',
      'Gato zen',
      'Delfín juguetón',
      'Panda sonriente',
      'Luciérnaga brillante',
      'Mariposa feliz',
      'Pingüino bailarín',
      'Capibara tranquila',
      'Tigre dulce',
      'Cangrejito coqueto',
      'Oveja amable',
      'Cerdito feliz',
      'Caballito feliz',
      'Perro amable',
      'Gato aventurero',
      'Oso sonriente',
      'Ardilla brillante',
      'Nutria tranquila',
      'Búho brillante',
      'Chispa de estrella',
      'Corazón de rana',
      'Aventura de conejo',
      'Sombra de zorro',
      'Truco de tortuga',
      'Sonrisa de panda',
      'Brillo de luciérnaga',
      'Alegría de delfín',
      'Faro de ballena',
    ],
    _ => const [
      'Happy Frog',
      'Sunny Cat',
      'Brave Fox',
      'Cozy Panda',
      'Smiling Dolphin',
      'Curious Owl',
      'Gentle Bear',
      'Shiny Rabbit',
      'Kind Koala',
      'Curious Chipmunk',
      'Dancing Penguin',
      'Friendly Hedgehog',
      'Chill Turtle',
      'Bright Firefly',
      'Playful Dolphin',
      'Joyful Otter',
      'Warm Capybara',
      'Cheerful Whale',
      'Brave Lion Cub',
      'Gentle Lion',
      'Smiling Squirrel',
      'Singing Dolphin',
      'Wandering Fox',
      'Silly Star',
      'Happy Hamster',
      'Cozy Beaver',
      'Lucky Rabbit',
      'Shiny Beetle',
      'Tiny Tiger',
      'Soft Bear',
      'Happy Octopus',
      'Gentle Giraffe',
      'Curious Seahorse',
      'Glowing Starfish',
      'Moonlit Cat',
      'Sunny Bunny',
      'Sparkle Panda',
      'Tranquil Crab',
      'Adventurous Dog',
      'Cozy Koala',
      'Brave Duckling',
      'Playful Puppy',
      'Charming Owl',
      'Calm Corgi',
      'Smile Parrot',
    ],
  };

  return options[rand.nextInt(options.length)];
}

